name: Expo Update to Preview

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🧹 Remove lock file and node_modules
        run: rm -rf node_modules package-lock.json

      - name: 🚀 Install Expo CLI
        run: npm install -g expo-cli

      - name: 📦 Install SDK-compatible dependencies
        run: expo install

      - name: 📡 Install EAS CLI
        run: npm install -g eas-cli

      - name: 🚀 Publish update to Expo Go
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          CI: 1
        run: eas update --branch preview --message "GitHub Action update"